project_id = "lqwsnhjavgdrfuzgdywy"

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.generate-daily-invoices]
verify_jwt = false

[functions.apply-due-rent-increments]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = true
